portfolio/employer/urls.py
from django.urls import path
from . import views
app_name = 'employer'

urlpatterns = [
    path('create_job_view', views.create_job_view, name='create_job_view'),
    path('emp_index', views.emp_index, name='emp_index'),
]

portfolio/loginapp/urls.py
from . import views
from django.urls import path
app_name = 'loginapp'
urlpatterns = [
    path('login', views.login_page, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),

]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('loginapp/',include('loginapp.urls')),
    path('jobseeker/',include('jobseeker.urls')),
    path('employer/', include('employer.urls')),
    path('captcha', include('captcha.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/loginapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_job_seeker = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

portfolio/loginapp/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from captcha.fields import CaptchaField
from .models import User


class SignUpForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1',
                  'password2', 'captcha')


class LoginForm(AuthenticationForm):
    captcha = CaptchaField()
    

portfolio/loginapp/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import SignUpForm, LoginForm
# Create your views here.
from django.contrib import messages
from .models import User

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_job_seeker = True
            user.save()
            return HttpResponseRedirect(reverse('loginapp:login'))
            # username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password')
            # user_var = authenticate(username=username, password=password)
            # if user_var is not None and user_var.is_job_seeker:
            #     login(request, user_var)
            #     messages.success(request,'Signed Up Successfully!')
            #     messages.info(request,'Remember! You can`t apply for Jobs untill You complete Your Profile!')
            #     return HttpResponseRedirect(reverse('jobseeker:profile'))


            # elif user_var is not None and user_var.is_admin:
            #     login(request,user_var)
            #     messages.success(request,'Signed Up Admin Successfully!')
            #     return HttpResponseRedirect(reverse('employer:create_job_view'))
            # else:
            #     return HttpResponse('Go away')
        else:
            # Print out the form errors to the console
            print(form.errors)
            # Add an error message to the messages framework
            messages.error(
                request, f'There was an error with your submission => {form.errors}')
    else:
        form = SignUpForm()

    return render(request, 'loginapp/signup.html', {'form': form})

def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_job_seeker:
                login(request, user)

                messages.success(request,'Logged In Successfully!')
                messages.info(request,'Remember You can`t apply for jobs untill you have completed your profile')
                return HttpResponseRedirect(reverse('jobseeker:profile'))
            elif user is not None and user.is_admin:
                login(request,user)
                messages.success(request,'Signed Up Admin Successfully!')
                return HttpResponseRedirect(reverse('employer:create_job_view'))
            else:
                return HttpResponse('Go away')
        else:
            # Print out the form errors to the console
            print(form.errors)
            # Add an error message to the messages framework
            messages.error(
                request, f'There was an error with your submission : {form.errors} Please try again.')

    dict = {'form': form}
    return render(request, 'loginapp/login.html', dict)

def logout_view(request):
    logout(request)
    messages.warning(request,'You are Logged Out!')
    return HttpResponseRedirect(reverse('loginapp:login'))

portfolio/templates/loginapp/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login Page</title>


</head>

<body>
    <!-- partial:index.partial.html -->
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <!-- Design by foolishdeveloper.com -->
        <title>Glassmorphism login Form Tutorial in html css</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
        <!-- jQuery library -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- Bootstrap JavaScript files -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
        <!--Stylesheet-->
        <style media="screen">
            *,
            *:before,
            *:after {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }

            body {
                background-color: #080710;
            }

            .background {
                width: 430px;
                height: 520px;
                position: absolute;
                transform: translate(-50%, -50%);
                left: 50%;
                top: 50%;
            }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

            .shape:first-child {
                background: linear-gradient(#1845ad,
                        #23a2f6);
                left: -80px;
                top: -80px;
            }

            .shape:last-child {
                background: linear-gradient(to right,
                        #ff512f,
                        #f09819);
                right: -100px;
                bottom: -80px;
            }

            form {
                height: 720PX;
                width: 400px;
                background-color: rgba(255, 255, 255, 0.13);
                position: absolute;
                transform: translate(-50%, -50%);
                top: 50%;
                left: 50%;
                border-radius: 10px;
                backdrop-filter: blur(10px);
                border: 2px solid rgba(255, 255, 255, 0.1);
                box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
                padding: 50px 35px;
            }

            form * {
                font-family: 'Poppins', sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

            label {
                display: block;
                margin-top: 30px;
                font-size: 16px;
                font-weight: 500;
            }

            input {
                display: block;
                height: 50px;
                width: 100%;
                background-color: rgba(255, 255, 255, 0.07);
                border-radius: 3px;
                padding: 0 10px;
                margin-top: 8px;
                font-size: 14px;
                font-weight: 300;
            }

            ::placeholder {
                color: #e5e5e5;
            }

            button {
                margin-top: 50px;
                width: 100%;
                background-color: #ffffff;
                color: #080710;
                padding: 15px 0;
                font-size: 18px;
                font-weight: 600;
                border-radius: 5px;
                cursor: pointer;
                transition: opacity 0.5s;

            }

            button:hover {
                opacity: 0.8;
            }

            button:active {
                opacity: 0.6;
            }

            .social {
                margin-top: 30px;
                display: flex;
            }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(255, 255, 255, 0.27);
                color: #eaf0fb;
                text-align: center;
            }

            .social div:hover {
                background-color: rgba(255, 255, 255, 0.47);
            }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }
        </style>
    </head>

    <body>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissible fade show {% if message.tags %}alert-{{ message.tags }}{% endif %}
                {% if message.tags == 'success' %}alert-success{% endif %}
                {% if message.tags == 'info' %}alert-info{% endif %}
                {% if message.tags == 'warning' %}alert-warning{% endif %}
                {% if message.tags == 'error' %}alert-danger{% endif %}" role="alert"
            style="display: flex; flex-direction: row;">
            <span>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                style="margin-top: 20px ; margin-right: 50px; padding: 0;"></button>
        </div>
        {% endfor %}
        {% endif %}


        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>
        <form method="post">
            {%csrf_token%}
            <h3>Login Here</h3>

            <label for="username">Username</label>
            {{form.username}}

            <label for="password">Password</label>
            {{form.password}}

            <label for="password">Captcha</label>
            {{form.captcha}}

            <button type="submit">Log In</button>
            <p style="margin-left: 50px; margin-top: 50px;"><a href="{%url 'loginapp:signup'%}">Don`t Have An
                    Account?</a></p>
        </form>
    </body>

    </html>
    <!-- partial -->

</body>

</html>

portfolio/templates/loginapp/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sign Up Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap JavaScript files -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">


</head>

<body>
    <!-- partial:index.partial.html -->
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <!-- Design by foolishdeveloper.com -->
        <title>Glassmorphism login Form Tutorial in html css</title>

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
        <!--Stylesheet-->
        <style media="screen">
            *,
            *:before,
            *:after {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }

            body {
                background-color: #080710;
            }

            .background {
                width: 430px;
                height: 520px;
                position: absolute;
                transform: translate(-50%, -50%);
                left: 50%;
                top: 50%;
            }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

            .shape:first-child {
                background: linear-gradient(#1845ad,
                        #23a2f6);
                left: -80px;
                top: -80px;
            }

            .shape:last-child {
                background: linear-gradient(to right,
                        #ff512f,
                        #f09819);
                right: -100px;
                bottom: -80px;
            }

            form {
                height: 930px;
                width: 400px;
                background-color: rgba(255, 255, 255, 0.13);
                position: absolute;
                transform: translate(-50%, -50%);
                top: 50%;
                left: 50%;
                border-radius: 10px;
                backdrop-filter: blur(10px);
                border: 2px solid rgba(255, 255, 255, 0.1);
                box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
                padding: 50px 35px;
                margin-top: 200px;
            }

            form * {
                font-family: 'Poppins', sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

            label {
                display: block;
                margin-top: 30px;
                font-size: 16px;
                font-weight: 500;
            }

            input {
                display: block;
                height: 50px;
                width: 100%;
                background-color: rgba(255, 255, 255, 0.07);
                border-radius: 3px;
                padding: 0 10px;
                margin-top: 8px;
                font-size: 14px;
                font-weight: 300;
            }

            ::placeholder {
                color: #e5e5e5;
            }

            button {
                margin-top: 50px;
                width: 100%;
                background-color: #ffffff;
                color: #080710;
                padding: 15px 0;
                font-size: 18px;
                font-weight: 600;
                border-radius: 5px;
                cursor: pointer;
                transition: opacity 0.5s;

            }

            button:hover {
                opacity: 0.8;
            }

            button:active {
                opacity: 0.6;
            }

            .social {
                margin-top: 30px;
                display: flex;
            }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(255, 255, 255, 0.27);
                color: #eaf0fb;
                text-align: center;
            }

            .social div:hover {
                background-color: rgba(255, 255, 255, 0.47);
            }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }
        </style>
    </head>

    <body>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissible fade show {% if message.tags %}alert-{{ message.tags }}{% endif %}
            {% if message.tags == 'success' %}alert-success{% endif %}
            {% if message.tags == 'info' %}alert-info{% endif %}
            {% if message.tags == 'warning' %}alert-warning{% endif %}
            {% if message.tags == 'error' %}alert-danger{% endif %}" role="alert" style="display: flex; flex-direction: row;">
            <span>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" style="margin-top: 20px ; margin-right: 50px; padding: 0;"></button>
        </div>
        {% endfor %}
        {% endif %}

        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>
        <form method="post">
            {%csrf_token%}
            <h3>Sign Up Here</h3>

            <label for="username">Username</label>
            {{form.username}}

            <label for="password">Password 1</label>
            {{form.password1}}

            <label for="password">Password 2</label>
            {{form.password2}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="password">Captcha</label>
            {{form.captcha}}

            <button type="submit"> Sign Up</button>
            <p style="margin-left: 75px; margin-top: 20px;"><a href="{%url 'loginapp:login'%}">Have An Account?</a></p>
            <div class="social">
                <div class="go"><i class="fab fa-google"></i> Google</div>
                <div class="fb"><i class="fab fa-facebook"></i> Facebook</div>
            </div>
        </form>
    </body>

    </html>
    <!-- partial -->

</body>

</html>